/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "movestack.c"
#include "pertag.c"
#include "restartsig.c"
#include "sticky.c"
#include "swallow.c"
#include "switchcol.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "warp.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_monocle.c"
#include "layout_tile.c"

